#!/bin/sh
#
# This script is called from 'startx' when you start an X session
#

export WINDOWMANAGER=${WINDOWMANAGER-spectrwm}



[ -f /etc/xprofile ] && . /etc/xprofile
[ -f $XDG_CONFIG_HOME/X11/xprofile ] && . $XDG_CONFIG_HOME/X11/xprofile


unset WINDOW_MANAGER STARTUP
exec $WINDOWMANAGER ${1+"$@"}

# call failsafe
exit 0
