#!/bin/sh
#
# This script is called from 'startx' when you start an X session
#


export WINDOWMANAGER=${p_wm-spectrwm}


#
# Add your own lines here...
#

[ -f $XDG_CONFIG_HOME/X11/xprofile ] && . $XDG_CONFIG_HOME/X11/xprofile


# Run startup apps
p_run_startup_apps

#
# finally start the window manager
#
unset WINDOW_MANAGER STARTUP
exec $WINDOWMANAGER ${1+"$@"}

# call failsafe
exit 0
