#!/usr/bin/env bash
# vim: set filetype=sh shiftwidth=2 :

for cmd in \
  'dunst' \
  'nm-applet' \
  'sxhkd' \
  'unclutter -idle 1' \
  'volumeicon'
do
  app=${cmd%%\ *}
  if [ ! $(which $app >/dev/null 2>&1) ]; then
    echo $cmd
    pkill $app >/dev/null 2>&1; $cmd &
  fi
done
