#!/bin/sh
# vim: set filetype=sh shiftwidth=2 :

SEP=' |'

print_mem() {
  MEM=`/usr/bin/top | grep Free: | cut -d " " -f6`
  echo -n "Free mem: $MEM  "
}

_print_cpu() {
  printf "CPU: %3d%% User %3d%% Nice %3d%% Sys %3d%% Spin %3d%% Int %3d%% Idle  " $1 $2 $3 $4 $5 $6
}

print_cpu() {
  OUT=""
  # iostat prints each column justified to 3 chars, so if one counter
  # is 100, it jams up agains the preceeding one. sort this out.
  while [ "${1}x" != "x" ]; do
    if [ ${1} -gt 99 ]; then
      OUT="$OUT ${1%100} 100"
    else
      OUT="$OUT ${1}"
    fi
    shift;
  done
  _print_cpu $OUT
}

print_cpuspeed() {
  CPU_SPEED=`/sbin/sysctl hw.cpuspeed | cut -d "=" -f2`
  printf "CPU speed: %4d MHz  " $CPU_SPEED
}

print_volume()
{
  ## Volume
  [ $(pulsemixer --get-mute) -eq 1 ] && volico='' || volico=''
  #vol=$(amixer -c 0 get Master | grep -o "[0-9]*%" | head -1)
  local vol=$(pulsemixer --get-volume | cut -d' ' -f1)

  echo -n "$SEP $volico $vol"
}

print_date_time()
{
  echo -n "$SEP $(date +'w%V, %a, %Y-%m-%d, %H:%M')"
}

print_bat()
{
  ## Battery
  powerdir=/sys/class/power_supply/
  if [ -e $powerdir/BAT0 ]; then
    sep=$SEP
    PWR=""
    for f in /sys/class/power_supply/BAT[0-9]
    do
      BATNAME=$(cat $f/*/name)
      batstat=$(cat $f/status)
      pwr=$(cat $f/capacity)
      if [ ! $batstat = "Charging" ] && [ ! $batstat = "Full" ]; then
        #   \uf240    \uf241   \uf242    \uf243    \uf244
        [ $pwr -lt 15 ] && pwrico=' '
        [ $pwr -ge 15 ] && pwrico=' '
        [ $pwr -gt 50 ] && pwrico=' '
        [ $pwr -gt 75 ] && pwrico=' '
        [ $pwr -gt 95 ] && pwrico=' '
      else
        pwrico='' #  \uf0e7
      fi
      PWR="$PWR$pwrico $pwr% "

      # If capacity is lower than 10% send notification
      if [ $BATNAME = "BAT0" ] && [ $pwr -lt 10 ]; then
        dunstify -u Critical "BATTERY: $pwr%"
      fi
    done
    echo -n "$SEP $PWR"
  fi
}

while true; do
  #print_cpu
  print_volume
  print_bat
  print_date_time
  echo ""
  sleep 10
done
