#!/bin/sh
# vim: set filetype=sh shiftwidth=2 :
# Script for adding magnet link or torrent file to transmission-daemon.
# Called from torrent.desktop

pgrep -x transmission-da >/dev/null || transmission-daemon; sleep 1s

transmission-remote --add "$@" && notify-send "Torrent added: $@"

