#!/bin/bash
#vim: filetype=sh

# this is a simple config for herbstluftwm

HERBSTDIR="$HOME/.config/herbstluftwm"

source "$HERBSTDIR/colors"

hc() { herbstclient "$@" ;}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

#hc keybind $Mod-Shift-q spawn dmenu_exit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-x close
#hc keybind $Mod-Return spawn ${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Shift-u   split   top     0.5
hc keybind $Mod-Shift-o   split   left    0.5
hc keybind $Mod-u         split   bottom  0.5
hc keybind $Mod-o         split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left  +$resizestep
hc keybind $Mod-Control-j       resize down  +$resizestep
hc keybind $Mod-Control-k       resize up    +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=("01" "02" "03" "04" "05" "06" "07" "08" "09" "10")
tag_keys=("1" "2" "3" "4" "5" "6" "7" "8" "9" "0")

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent


# rules
hc unrule -F
hc rule focus=on # normally focus new clients
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off


#### VISUAL SETTINGS ####

    # theme
    xsetroot -solid $co_root

    hc set always_show_frame 1
    hc set frame_bg_transparent 1
    hc set frame_transparent_width 1

    hc set smart_frame_surroundings 15
    hc set frame_border_width 2

    hc set frame_border_active_color $co_frame_border_active_color
    hc set frame_border_normal_color "$co_frame_border_normal_color"

    hc set frame_bg_normal_color $co_root
    hc set frame_bg_active_color $co_root

    hc set frame_gap 5
    hc set frame_padding 0

    hc set window_gap 3
    hc set smart_window_surroundings 0
    hc set mouse_recenter_gap 0

    hc attr theme.tiling.reset 1
    hc attr theme.floating.reset 1
    hc attr theme.active.color $co_window_active_color
    hc attr theme.normal.color $co_window_normal_color
    hc attr theme.urgent.color $co_window_urgent_color
    hc attr theme.inner_width 0
    hc attr theme.border_width 4

    hc attr theme.floating.border_width 4
    hc attr theme.floating.outer_width 1
    hc attr theme.floating.outer_color black

    hc set tree_style '╾│ ├└╼─┐'

    # unlock, just to be sure
    hc unlock



#### PANEL SETUP ####

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=$HERBSTDIR/panel.sh
kill lemonbar
killall $panel
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done


#$HOME/bin/p_run_startup_apps &
